### ISSUE TITLE
是否考虑把文档放在GitHub Pages上

### ISSUE THREAD

**Issue by mengguyi** [BililiveRecorder/website#12]
现在的文档托管在cloudflare pages上，由于不可抗拒的因素cloudflare很慢

但是GitHub Pages不慢，所以是否考虑托管在GitHub Pages上，一来便于管理二来方便访问

**Comment by Genteure** [comment]
之前看的是访问 cloudflare 比 GitHub Pages 更快，所以就用的 cloudfalre。
而且现在有用到 CloudFlare Pages Function / Worker 所以还是不搬了
